### ISSUE TITLE
NullPointer when hymapping not has the same name

### ISSUE THREAD

**Issue by Kogoro** [DarwinSPL/DarwinSPL#4]
It should create a problem marker or something else instead.

```
java.lang.NullPointerException
	at eu.hyvar.feature.util.HyFeatureResolverUtil.resolveFeature(HyFeatureResolverUtil.java:39)
	at eu.hyvar.feature.expression.util.HyExpressionResolverUtil.resolveFeature(HyExpressionResolverUtil.java:47)
	at eu.hyvar.feature.expression.resource.hyexpression.analysis.HyAbstractFeatureReferenceExpressionFeatureReferenceResolver.resolve(HyAbstractFeatureReferenceExpressionFeatureReferenceResolver.java:22)
	at eu.hyvar.feature.mapping.resource.hymapping.analysis.HyAbstractFeatureReferenceExpressionFeatureReferenceResolver.resolve(HyAbstractFeatureReferenceExpressionFeatureReferenceResolver.java:21)
	at eu.hyvar.feature.mapping.resource.hymapping.analysis.HyAbstractFeatureReferenceExpressionFeatureReferenceResolver.resolve(HyAbstractFeatureReferenceExpressionFeatureReferenceResolver.java:1)
	at eu.hyvar.feature.mapping.resource.hymapping.mopp.HymappingContextDependentURIFragment.resolve(HymappingContextDependentURIFragment.java:61)
	at eu.hyvar.feature.mapping.resource.hymapping.mopp.HymappingResource.getEObject(HymappingResource.java:444)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:201)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:261)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at eu.hyvar.feature.expression.impl.HyAbstractFeatureReferenceExpressionImpl.getFeature(HyAbstractFeatureReferenceExpressionImpl.java:124)
	at eu.hyvar.feature.expression.impl.HyAbstractFeatureReferenceExpressionImpl.eGet(HyAbstractFeatureReferenceExpressionImpl.java:195)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
	at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:439)
	at eu.hyvar.feature.mapping.resource.hymapping.util.HymappingInterruptibleEcoreResolver.resolveCrossReferences(HymappingInterruptibleEcoreResolver.java:81)
	at eu.hyvar.feature.mapping.resource.hymapping.util.HymappingInterruptibleEcoreResolver.resolveAll(HymappingInterruptibleEcoreResolver.java:76)
	at eu.hyvar.feature.mapping.resource.hymapping.util.HymappingInterruptibleEcoreResolver.resolveAll(HymappingInterruptibleEcoreResolver.java:56)
	at eu.hyvar.feature.mapping.resource.hymapping.mopp.HymappingResource.resolveAfterParsing(HymappingResource.java:632)
	at eu.hyvar.feature.mapping.resource.hymapping.mopp.HymappingResource.reload(HymappingResource.java:343)
	at eu.hyvar.feature.mapping.resource.hymapping.ui.HymappingBackgroundParsingStrategy$ParsingJob.run(HymappingBackgroundParsingStrategy.java:107)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by mnieke** [comment]
Happens when a mapping is created with the wrong file name (not matching the feature model file name).

**Comment by guidanceicse2018** [comment]
Added a null check so that this exception won't appear anymore.
However, as this editor is generated, we only have limited access to its code.
So a popup if there is no feature model available would take too much effort.
Instead, when creating a mapping file, it is now ensured that a corresponding feature model exists.
Problems still occur if the feature model is deleted afterwards.

**Comment by mnieke** [comment]
Added a null check so that this exception won't appear anymore.
However, as this editor is generated, we only have limited access to its code.
So a popup if there is no feature model available would take too much effort.
Instead, when creating a mapping file, it is now ensured that a corresponding feature model exists.
Problems still occur if the feature model is deleted afterwards.
