### ISSUE TITLE
Export SVG isn't working

### ISSUE THREAD

**Issue by mnieke** [DarwinSPL/DarwinSPL#77]
Not urgent, but please have a look. When a feature model is opened and I hit the button "Export SVG Image", many errors are coming in.

NullPointer blow, but please verify that the function is working.
!ENTRY org.eclipse.ui 4 0 2018-02-19 09:57:24.889
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at de.darwinspl.feature.graphical.base.model.DwFeatureWrapped.hasModfierAtDate(DwFeatureWrapped.java:199)
	at de.darwinspl.feature.graphical.base.figures.DwFeatureTypeFigure.getBounds(DwFeatureTypeFigure.java:37)
	at org.eclipse.draw2d.Figure.containsPoint(Figure.java:316)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:384)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Layer.findFigureAt(Layer.java:54)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Layer.findFigureAt(Layer.java:54)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Layer.findFigureAt(Layer.java:54)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Layer.findFigureAt(Layer.java:54)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Layer.findFigureAt(Layer.java:54)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Figure.findDescendantAtExcluding(Figure.java:357)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:388)
	at org.eclipse.draw2d.Figure.findFigureAt(Figure.java:377)
	at org.eclipse.draw2d.SWTEventDispatcher.updateFigureUnderCursor(SWTEventDispatcher.java:573)
	at org.eclipse.draw2d.SWTEventDispatcher.receive(SWTEventDispatcher.java:367)
	at org.eclipse.draw2d.SWTEventDispatcher.dispatchMouseMoved(SWTEventDispatcher.java:252)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseMoved(DomainEventDispatcher.java:357)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseMove(LightweightSystem.java:543)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:213)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by roehrsi** [comment]
What were your exact steps? I could not reproduce this in the current master branch.
I encountered (and fixed) a similar issue in #76, where `type.getType()` of `HyGroupType` would return null, when there were no valid group types at t=null.

This happened when changing the date to null:

> !ENTRY org.eclipse.ui 4 0 2018-03-28 15:00:45.172
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at de.darwinspl.feature.graphical.base.editparts.DwGroupEditPart.createToolTipText(DwGroupEditPart.java:125)
	at de.darwinspl.feature.graphical.base.editparts.DwGroupEditPart.updateFigure(DwGroupEditPart.java:103)
	at de.darwinspl.feature.graphical.base.editparts.DwGroupEditPart.refreshVisuals(DwGroupEditPart.java:96)
	at de.darwinspl.feature.graphical.editor.editparts.DwGroupEditorEditPart.refreshVisuals(DwGroupEditorEditPart.java:157)
	at de.darwinspl.feature.graphical.editor.editparts.DwGroupEditorEditPart.propertyChange(DwGroupEditorEditPart.java:107)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at de.darwinspl.feature.graphical.base.model.DwEditorChangeableElement.notifyProperyChange(DwEditorChangeableElement.java:51)
	at de.darwinspl.feature.graphical.base.model.DwEvolutionaryPositionElement.addPosition(DwEvolutionaryPositionElement.java:69)
	at de.darwinspl.feature.graphical.base.model.DwFeatureModelWrapped.rearrangeFeatures(DwFeatureModelWrapped.java:475)
	at de.darwinspl.feature.graphical.base.editparts.DwFeatureModelEditPart.propertyChange(DwFeatureModelEditPart.java:81)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at de.darwinspl.feature.graphical.base.model.DwFeatureModelWrapped.setSelectedDate(DwFeatureModelWrapped.java:220)
	at de.darwinspl.feature.graphical.base.editor.DwGraphicalFeatureModelViewer.setCurrentSelectedDate(DwGraphicalFeatureModelViewer.java:112)
	at de.darwinspl.feature.graphical.base.editor.DwGraphicalFeatureModelViewer.handleEvent(DwGraphicalFeatureModelViewer.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1120)
	at org.eclipse.swt.widgets.Scale.wmScrollChild(Scale.java:594)
	at org.eclipse.swt.widgets.Control.WM_HSCROLL(Control.java:5124)
> ...


Also, the .svg is created correctly for me.
