### ISSUE TITLE
Anomaly view analyzed without feature model open

### ISSUE THREAD

**Issue by mnieke** [DarwinSPL/DarwinSPL#80]
Just a small bug:
If I change the server address in the anomaly view without having an FM opened, it still tries to analyze something.
As a result, I retrieve the following NullPointerException:
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView.getFile(DwAnomalyView.java:566)
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView.modelFileExists(DwAnomalyView.java:574)
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView.getAnomalies(DwAnomalyView.java:599)
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView.setInputOfViewers(DwAnomalyView.java:380)
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView.refresh(DwAnomalyView.java:458)
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView.access$2(DwAnomalyView.java:449)
	at de.darwinspl.feature.graphical.configurator.editor.anomaly.views.DwAnomalyView$4.run(DwAnomalyView.java:282)
...

**Comment by alahola** [comment]
@mnieke I handled the exception. Now, if no feature model is opened when changing the server address, the last opened feature model is used for the analyzation. Is that fine? Or should there be a message that a feature model needs to be opened?

**Comment by mnieke** [comment]
@alahola I would rather create a message saying that a feature model needs to be opened. Otherwise it may be confusing where these values come from.
